Fabulously-Optimized/wiki

- en-us/multimc-auto-update.md
Relation: https://github.com/Fabulously-Optimized/fabulously-optimized/pull/290
> Info for `pre-launch.sh` and `post-exit.sh`

- en-us/multimc-auto-update.md
Requires https://github.com/Fabulously-Optimized/fabulously-optimized/pull/307
(I might've taken a *tiny* bit of inspiration from RaptaG's Linux tutorial!)
> Add Windows instructions

- en-us/give-up-optifine.md
> Improve Give up OptiFine

- en-us/give-up-optifine.md
> Update OptiFine Zoom Docs

- en-us/update-instructions.md
Clarifies the update description a bit for MultiMC.
> Fix MultiMC update instructions

- en-us/server-setup.md
1. This ensures we are targetting the 1.19+ backend servers as anything older than that will not ship with the enforce-secure-profile context in any way,
2. The Bungeecord / Waterfall proxy context should be included which tons of servers still use to this day and is best to be discussed about aswell if the user does not have velocity as their proxy,
3. Finally; FreedomChat has been chosen to be a comfortable plugin for usage in spigot and it's forks as it is genuinely safer for usage and doesn't cause breakage with other chat-related plugins.
*(Edits are welcomed)*
> Ensure bungee is discussed and correct backend stuff.

- en-us/server-setup.md
This fixes a few typos in the entire server setup guide and introduces 3 new configs for FreedomChat itself.
> Add 3 required configs for FreedomChat, Fix typos.

- en-us/changed-options.md
This swaps out the 5th table's wording a bit as it sounded a bit bizarre in speech sense.
> "Why Changed?" -> "Reason for Change".

- en-us/install-instructions.md
> Add instructions on how to run the game

- en-us/install-instructions.md
- en-us/update-instructions.md
Title explains everything - Although new documentation is welcomed in case we need to actually include new notes for step 1.
> 0.14.12 is confirmed working on older clients.

- en-us/language-support.md
Waiting on https://github.com/Fabulously-Optimized/fabulously-optimized/pull/573 to fully complete
> Resourcepacks -> Resource Packs

- language-support.md
> Fix Fabric API creative tabs translation url

- language-support.md
> Fix more translation url

- install-instructions.md
- update-instructions.md
> Steam Deck instructions

- language-support.md
> Update Branch to Default

- .github/workflows/git-repo-sync.yml
robotkoer requested me to sync the step update here: Part 3.
> Update checkout to v4.

- listing-description/en-US.md
> Listing description update

- give-up-optifine.md
> Custom colors

- language-support.md
> Remove RTL notice 

- adding-more-mods.md
- backup-and-uninstall.md
- disabling-mods.md
- install-instructions.md
- update-instructions.md
- vanilla-launcher-faq.md
> New page and improvements

- adding-more-mods.md
- backup-and-uninstall.md
- disabling-mods.md
- install-instructions.md
- update-instructions.md
> Modrinth App 0.9.2
